apiVersion: apps/v1
kind: Deployment
metadata:
  name: brezyweather
spec:
  replicas: 4
  selector:
    matchLabels:
      app: brezyweather
      version: '1.0'
  template:
    metadata:
      labels:
        app: brezyweather
        version: '1.0'
    spec:
      containers:
      - name: brezyweather
        image: codewithpraveen/labs-k8s-brezyweather:1.0
        ports:
        - containerPort: 80